
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafael
 */
public class BPMW extends javax.swing.JFrame {

    /**
     * Creates new form BPMW
     */
    public BPMW() {
        initComponents();
    }
    
    BPM bpMode = new BPM();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMW = new javax.swing.JPanel();
        TittleBot = new javax.swing.JLabel();
        TittleTop = new javax.swing.JLabel();
        BPM_btn = new javax.swing.JButton();
        BTM_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batch Processing - Main Window");
        setResizable(false);

        PanelMW.setBackground(new java.awt.Color(255, 255, 255));

        TittleBot.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        TittleBot.setText("Processing");

        TittleTop.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        TittleTop.setText("Batch");

        BPM_btn.setText("Batch Preparation Mode");
        BPM_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPM_btnActionPerformed(evt);
            }
        });

        BTM_btn.setText("Batch Threding Mode");

        javax.swing.GroupLayout PanelMWLayout = new javax.swing.GroupLayout(PanelMW);
        PanelMW.setLayout(PanelMWLayout);
        PanelMWLayout.setHorizontalGroup(
            PanelMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMWLayout.createSequentialGroup()
                .addGroup(PanelMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMWLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(TittleTop))
                    .addGroup(PanelMWLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(TittleBot))
                    .addGroup(PanelMWLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(PanelMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTM_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPM_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        PanelMWLayout.setVerticalGroup(
            PanelMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMWLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TittleTop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TittleBot)
                .addGap(18, 18, 18)
                .addComponent(BPM_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BTM_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BPM_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPM_btnActionPerformed
        // TODO add your handling code here:
        if(this.bpMode.isShowing()){
            // Cannot open another instance for this window
            JOptionPane.showMessageDialog(null, "Batch Preparation Mode window is already active!");
        }else {
            this.bpMode.setVisible(true);
        }
    }//GEN-LAST:event_BPM_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BPMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BPMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BPMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BPMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BPMW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPM_btn;
    private javax.swing.JButton BTM_btn;
    private javax.swing.JPanel PanelMW;
    private javax.swing.JLabel TittleBot;
    private javax.swing.JLabel TittleTop;
    // End of variables declaration//GEN-END:variables
}
